# Generated by Django 3.0.5 on 2020-04-16 14:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200416_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.UUIDField(default=uuid.UUID('5f91d43b-f7b2-481a-a156-aff986e22cd5'), primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='FilmInstance',
        ),
    ]
