# Generated by Django 3.0.5 on 2020-04-16 14:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200416_1707'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actor',
            new_name='Producer',
        ),
        migrations.RemoveField(
            model_name='film',
            name='actors',
        ),
        migrations.AddField(
            model_name='film',
            name='producer',
            field=models.ForeignKey(help_text='Выберите режиссёра', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Producer'),
        ),
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.UUIDField(default=uuid.UUID('203079aa-5234-49b3-972b-0327c7a9b6d9'), primary_key=True, serialize=False),
        ),
    ]
