# Generated by Django 3.0.5 on 2020-04-19 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200416_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='poster',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='producer',
            name='photo',
            field=models.ImageField(upload_to='media'),
        ),
    ]
